### ISSUE TITLE
How to edit css

### ISSUE THREAD

**Issue by drupalspec** [lon-yang/ngx-markdown-editor#19]
Hello in our project we need to change editor css in some places. How I should do this? If I use styleUrl path from my component it's doesn't work.

**Comment by lon-yang** [comment]
oh. the `/deep/` has been deprecated. so try write the class in global.
e.g.
```css
md-editor .md-editor-container {
  background: black
}
```
