### ISSUE TITLE
If the sentence is so long that the preview can't show on one line,the preview can't show it correctly.

### ISSUE THREAD

**Issue by Math312** [lon-yang/ngx-markdown-editor#31]
When i input the sentence like this:

`ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd`

the preview will be out of shape like this:
![图片](https://user-images.githubusercontent.com/17799152/57067677-3c449300-6d02-11e9-8efd-6319a39c3de0.png)

How can I solve this problem?

**Comment by lon-yang** [comment]
Please add those style to your global style or somewhere.
```css
md-editor .editor-container .preview-panel {
  word-break: break-word;
}
```
